In [94]:
# examine the duckdb database, econ_facts table and master_en and fa tables

import duckdb
path = "/Users/alirezaranjipour/Documents/Work/IOD/IOD_Data_Dash/IOD-d_d_last_version/data/duckdb/iod_dash.duckdb"
con = duckdb.connect(path, read_only=True)

facts = con.execute("SELECT * FROM econ_facts").fetchdf()
master_en = con.execute("SELECT * FROM master_en").fetchdf()
master_fa = con.execute("SELECT * FROM master_fa").fetchdf()
geo = con.execute("SELECT * FROM geo").fetchdf()
sub = con.execute("SELECT * FROM sub").fetchdf()

print(facts.columns.tolist())
print(master_en.columns.tolist())
print(master_fa.columns.tolist())
print(geo.columns.tolist())
print(sub.columns.tolist())

print(master_en[['topic_id', 'indicator_label']].head())

con.close()

['topic_id', 'indicator_label', 'Source', 'calendar', 'time_id', 'value', 'unit', 'geo_code', 'geo_label', 'sub_code', 'sub_label', 'detail', 'detail_fa', 'fact_table']
['topic_id', 'level', 'main_category', 'sub_1', 'sub_2', 'sub_3', 'sub_4', 'sub_5', 'sub_6', 'sub_7', 'sub_8', 'sub_9', 'sub_10', 'indicator_label', 'calendar', 'geo_level', 'default_source', 'default_unit', 'frequency', 'requires_time_selection', 'chart_type', 'id_type', 'val_type', 'access']
['topic_id', 'level', 'main_category', 'sub_1', 'sub_2', 'sub_3', 'sub_4', 'sub_5', 'sub_6', 'sub_7', 'sub_8', 'sub_9', 'sub_10', 'indicator_label', 'calendar', 'geo_level', 'default_source', 'default_unit', 'frequency', 'requires_time_selection', 'chart_type', 'id_type', 'val_type', 'access']
['geo_level', 'geo_code', 'geo_label_en', 'geo_label_fa', 'latitude', 'longitude']
['sub_code', 'sub_label_en', 'sub_label_fa']
         topic_id                               indicator_label
0      gdp_cur_wb        GDP nominal current price (World Bank)
1  gdp_cur_wb_irr  GDP nominal current price (World Bank - IRR)
2     gdp_cur_imf               GDP nominal current price (IMF)
3     gdp_cur_cbi      GDP nominal current price (CBI - yearly)
4  gdp_cur_cbi_se    GDP nominal current price (CBI - seasonal)

In [95]:
datasets = master_fa["main_category"].dropna().unique().tolist()
datasets

['01-اقتصاد کلان',
 '06-بازار',
 '05-انرژی',
 '02-اجتماعی',
 '03-سلامت',
 '07-تحارت گمرکی']

In [96]:

from doctest import master


df_fa = (
    facts[['topic_id','time_id','value','geo_code','sub_code', 'detail_fa']]
    .merge(
        master_fa[[ 'topic_id', 'indicator_label', 'default_unit', 'calendar', 'default_source']].drop_duplicates(subset='topic_id'),
        on="topic_id",
        how="left",
        validate="many_to_one"
    )
    .merge(
        geo[['geo_code', 'geo_label_fa']].drop_duplicates(subset='geo_code'),
        on="geo_code",
        how="left",
        validate="many_to_one"
    )
    .merge(
        sub[['sub_code', 'sub_label_fa']].drop_duplicates(subset='sub_code'),
        on="sub_code",
        how="left",
        validate="many_to_one"
    )
    .rename(columns={'geo_label_fa': 'geo_name', 'sub_label_fa': 'sub_label'})
)

df_fa = df_fa[
    ['indicator_label','geo_name', 'sub_label', 'time_id', 'value', 'default_unit', 'calendar', 'default_source', 'detail_fa']]
df_fa

,indicator_label,geo_name,sub_label,time_id,value,default_unit,calendar,default_source,detail_fa
0,تولید ناخالص داخلی به قیمت جاری (بانک جهانی),ایران,NaN,1960,4.20,میلیارد دلار,میلادی,بانک جهانی,None
1,تولید ناخالص داخلی به قیمت جاری (بانک جهانی),ایران,NaN,1961,4.43,میلیارد دلار,میلادی,بانک جهانی,None
2,تولید ناخالص داخلی به قیمت جاری (بانک جهانی),ایران,NaN,1962,4.69,میلیارد دلار,میلادی,بانک جهانی,None
3,تولید ناخالص داخلی به قیمت جاری (بانک جهانی),ایران,NaN,1963,4.93,میلیارد دلار,میلادی,بانک جهانی,None
4,تولید ناخالص داخلی به قیمت جاری (بانک جهانی),ایران,NaN,1964,5.38,میلیارد دلار,میلادی,بانک جهانی,None
...,...,...,...,...,...,...,...,...,...
37863,مشعل‌سوزی,ایران,NaN,2020,13.3,میلیارد متر مکعب,میلادی,بانک جهانی,None
37864,مشعل‌سوزی,ایران,NaN,2021,17.4,میلیارد متر مکعب,میلادی,بانک جهانی,None
37865,مشعل‌سوزی,ایران,NaN,2022,17.4,میلیارد متر مکعب,میلادی,بانک جهانی,None
37866,مشعل‌سوزی,ایران,NaN,2023,20.4,میلیارد متر مکعب,میلادی,بانک جهانی,None
37867,مشعل‌سوزی,ایران,NaN,2024,22.8,میلیارد متر مکعب,میلادی,بانک جهانی,None

In [88]:
df_en = (
    facts[['topic_id','time_id','value','geo_code','sub_code', 'detail']]
    .merge(
        master_en[[ 'topic_id', 'indicator_label', 'default_unit', 'calendar', 'default_source']].drop_duplicates(subset='topic_id'),
        on="topic_id",
        how="left",
        validate="many_to_one"
    )
    .merge(
        geo[['geo_code', 'geo_label_en']].drop_duplicates(subset='geo_code'),
        on="geo_code",
        how="left",
        validate="many_to_one"
    )
    .merge(
        sub[['sub_code', 'sub_label_en']].drop_duplicates(subset='sub_code'),
        on="sub_code",
        how="left",
        validate="many_to_one"
    )
    .rename(columns={'geo_label_en': 'geo_name', 'sub_label_en': 'sub_label'})
)

df_en = df_en[
    ['indicator_label','geo_name', 'sub_label', 'time_id', 'value', 'default_unit', 'calendar', 'default_source', 'detail']]
df_en

,indicator_label,geo_name,sub_label,time_id,value,default_unit,calendar,default_source,detail
0,GDP nominal current price (World Bank),Iran,NaN,1960,4.20,Billion US$,gregorian,World Bank,None
1,GDP nominal current price (World Bank),Iran,NaN,1961,4.43,Billion US$,gregorian,World Bank,None
2,GDP nominal current price (World Bank),Iran,NaN,1962,4.69,Billion US$,gregorian,World Bank,None
3,GDP nominal current price (World Bank),Iran,NaN,1963,4.93,Billion US$,gregorian,World Bank,None
4,GDP nominal current price (World Bank),Iran,NaN,1964,5.38,Billion US$,gregorian,World Bank,None
...,...,...,...,...,...,...,...,...,...
42967,Gas flaring,Iran,NaN,2020,13.3,billion m3,gregorian,World Bank,None
42968,Gas flaring,Iran,NaN,2021,17.4,billion m3,gregorian,World Bank,None
42969,Gas flaring,Iran,NaN,2022,17.4,billion m3,gregorian,World Bank,None
42970,Gas flaring,Iran,NaN,2023,20.4,billion m3,gregorian,World Bank,None
42971,Gas flaring,Iran,NaN,2024,22.8,billion m3,gregorian,World Bank,None

In [97]:
sub.columns.tolist()

['sub_code', 'sub_label_en', 'sub_label_fa']

In [90]:
# ---------------- Language configuration ---------------- #

LANG_CONFIG = {
    "en": {
        
            "sub_1": "Select",
            "sub_2": "Select",
            "sub_3": "Select",
            "sub_4": "Select",
            "sub_5": "Select",
            "sub_6": "Select",
            "sub_7": "Select",
            "sub_8": "Select",
            "sub_9": "Select",
            "sub_10": "Select",            
        },
    },
    "fa": {
            "title": "داشبورد داده‌های باز ایران",
            "language_label": "زبان",
            "selection_header": "انتخاب",
            "main_category": "بخش‌های اصلی",
            "dataset": "بخش",
            "option1": "انتخاب",
            "option2": "انتخاب",
            "option3": "انتخاب",
            "option4": "انتخاب",
            "option5": "انتخاب",
            "option6": "انتخاب",
            "option7": "انتخاب",
            "option8": "انتخاب",
            "option9": "انتخاب",
            "option10": "انتخاب",
            "source": "منبع",
            "frequency": "دوره زمانی",
            "calendar": "تقویم",
            "topic": "موضوع",
            "time_select": "زمان",
            "path": "مسیر:",
            "data_header": "داده‌ها",
            "chart_header": "نمودار",
            "time": "زمان",
            "value": "مقدار",
        },
    },
}

'\nLANG_CONFIG = {\n    "en": {\n        "label": "English",\n        "master_table": "master_en",      \n        "detail_column": "detail",        \n        "strings": {\n            "title": "IOD Dashboard",\n            "language_label": "Language",\n            "selection_header": "Selection",\n            "main_category": "Dataset",\n            "dataset": "Dataset",\n            "option1": "Option 1",\n            "option2": "Option 2",\n            "option3": "Option 3",\n            "option4": "Option 4",\n            "option5": "Option 5",\n            "option6": "Option 6",\n            "option7": "Option 7",\n            "option8": "Option 8",\n            "option9": "Option 9",\n            "option10": "Option 10",\n            "source": "Source",\n            "frequency": "Frequency",\n            "calendar": "Calendar",\n            "topic": "Topic",\n            "time_select": "Time",\n            "path": "Path:",\n            "data_header": "Data",\n            "chart_header": "Chart",\n            "time": "Time",\n            "value": "Value",\n        },\n    },\n    "fa": {\n        "label": "فارسی",\n        "master_table": "master_fa",      # FA metadata\n        "detail_column": "detail_fa",     # column in econ_facts\n        "strings": {\n            "title": "داشبورد داده\u200cهای باز ایران",\n            "language_label": "زبان",\n            "selection_header": "انتخاب",\n            "main_category": "بخش\u200cهای اصلی",\n            "dataset": "بخش",\n            "option1": "انتخاب",\n            "option2": "انتخاب",\n            "option3": "انتخاب",\n            "option4": "انتخاب",\n            "option5": "انتخاب",\n            "option6": "انتخاب",\n            "option7": "انتخاب",\n            "option8": "انتخاب",\n            "option9": "انتخاب",\n            "option10": "انتخاب",\n            "source": "منبع",\n            "frequency": "دوره زمانی",\n            "calendar": "تقویم",\n            "topic": "موضوع",\n            "time_select": "زمان",\n            "path": "مسیر:",\n            "data_header": "داده\u200cها",\n            "chart_header": "نمودار",\n            "time": "زمان",\n            "value": "مقدار",\n        },\n    },\n}\n'

In [98]:
df_en[(df_en['indicator_label'] == 'Provincial CPI - Iran Stats (1400 = 100)') & (df_en['time_id'] == '1400-08')].sort_values('geo_name')

,indicator_label,geo_name,sub_label,time_id,value,default_unit,calendar,default_source,detail
19215,Provincial CPI - Iran Stats (1400 = 100),Alborz,NaN,1400-08,104.60,None,persian,Iran Stats,Base year 1400
19039,Provincial CPI - Iran Stats (1400 = 100),Alborz,NaN,1400-08,104.60,None,persian,Iran Stats,Base year 1400
17279,Provincial CPI - Iran Stats (1400 = 100),Ardabil,NaN,1400-08,104.40,None,persian,Iran Stats,Base year 1400
17103,Provincial CPI - Iran Stats (1400 = 100),Ardabil,NaN,1400-08,105.00,None,persian,Iran Stats,Base year 1400
16927,Provincial CPI - Iran Stats (1400 = 100),Ardabil,NaN,1400-08,105.00,None,persian,Iran Stats,Base year 1400
...,...,...,...,...,...,...,...,...,...
10063,Provincial CPI - Iran Stats (1400 = 100),West Azerbaijan,NaN,1400-08,105.10,None,persian,Iran Stats,Base year 1400
16047,Provincial CPI - Iran Stats (1400 = 100),Yazd,NaN,1400-08,104.30,None,persian,Iran Stats,Base year 1400
15871,Provincial CPI - Iran Stats (1400 = 100),Yazd,NaN,1400-08,104.30,None,persian,Iran Stats,Base year 1400
15343,Provincial CPI - Iran Stats (1400 = 100),Zanjan,NaN,1400-08,105.40,None,persian,Iran Stats,Base year 1400
15167,Provincial CPI - Iran Stats (1400 = 100),Zanjan,NaN,1400-08,105.40,None,persian,Iran Stats,Base year 1400

In [92]:
facts[(facts['indicator_label'] == 'Provincial CPI - Iran Stats (1400 = 100)') & (facts['time_id'] == '1400-08')].sort_values('geo_label')

,topic_id,indicator_label,Source,calendar,time_id,value,unit,geo_code,geo_label,sub_code,sub_label,detail,detail_fa,fact_table
19215,cpi_irs_c_prov,Provincial CPI - Iran Stats (1400 = 100),Iran Stats,persian,1400-08,104.60,None,IR-05,Alborz,None,None,Base year 1400,سال پایه ۱۴۰۰,inflation_facts
19039,cpi_irs_c_prov,Provincial CPI - Iran Stats (1400 = 100),Iran Stats,persian,1400-08,104.60,None,IR-05,Alborz,None,None,Base year 1400,سال پایه ۱۴۰۰,inflation_facts
17279,cpi_irs_c_prov,Provincial CPI - Iran Stats (1400 = 100),Iran Stats,persian,1400-08,104.40,None,IR-03,Ardabil,None,None,Base year 1400,سال پایه ۱۴۰۰,inflation_facts
17103,cpi_irs_c_prov,Provincial CPI - Iran Stats (1400 = 100),Iran Stats,persian,1400-08,105.00,None,IR-03,Ardabil,None,None,Base year 1400,سال پایه ۱۴۰۰,inflation_facts
16927,cpi_irs_c_prov,Provincial CPI - Iran Stats (1400 = 100),Iran Stats,persian,1400-08,105.00,None,IR-03,Ardabil,None,None,Base year 1400,سال پایه ۱۴۰۰,inflation_facts
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10063,cpi_irs_c_prov,Provincial CPI - Iran Stats (1400 = 100),Iran Stats,persian,1400-08,105.10,None,IR-02,West Azerbaijan,None,None,Base year 1400,سال پایه ۱۴۰۰,inflation_facts
16047,cpi_irs_c_prov,Provincial CPI - Iran Stats (1400 = 100),Iran Stats,persian,1400-08,104.30,None,IR-31,Yazd,None,None,Base year 1400,سال پایه ۱۴۰۰,inflation_facts
15871,cpi_irs_c_prov,Provincial CPI - Iran Stats (1400 = 100),Iran Stats,persian,1400-08,104.30,None,IR-31,Yazd,None,None,Base year 1400,سال پایه ۱۴۰۰,inflation_facts
15343,cpi_irs_c_prov,Provincial CPI - Iran Stats (1400 = 100),Iran Stats,persian,1400-08,105.40,None,IR-14,Zanjan,None,None,Base year 1400,سال پایه ۱۴۰۰,inflation_facts
15167,cpi_irs_c_prov,Provincial CPI - Iran Stats (1400 = 100),Iran Stats,persian,1400-08,105.40,None,IR-14,Zanjan,None,None,Base year 1400,سال پایه ۱۴۰۰,inflation_facts

In [110]:

subs_list = [f"sub_{i}" for i in range(1, 11)]

options_list = []
for item in subs_list:
    options_list.extend(master_en[item].dropna().unique().tolist())

raw_list = (
    options_list
    + master_en["main_category"].dropna().unique().tolist()
    + master_fa["main_category"].dropna().unique().tolist()
)

clean_list = [x[3:] for x in raw_list]
print(len(raw_list),raw_list)
print(len(clean_list),clean_list)

239 ['01-GDP', '02-Inflation', '01-Exchange', '02-Gold', '03-Stock', '04_Monetary', '03-Labour force', '02-Supply & Demand', '01-Oil & Gas', '01-Population', '02-Vital', '03-Harms', '01-Life expectancy', '01-by Country', '02-by Customs', '01-Total Value', '02-Per capita', '01-National', '02-Provincial', '01-USD $', '02-Weighted', '01-Coin', 'Tehran Stock Market', '01-Broad money', '02-Monetary base', '01-Supply', '02-Demand', '01-OIl', '02-Natural gas', '03-Petrolium', '01-Population', '02-Household', '03-Marriage', '04-Divorce', '01-Birth', '02-Death', '01-Rubbery', '02-Suspicious Deaths', '03-Child marriage', '01-Male & Female', '02-Male', '03-Female', '01-Export', '02-Import', '03-Total trade', '02-Nominal', '03-PPP', '01-Growth', '04-Provincial', '01-Rate', '02-CPI', '1-Free price', '2-Nima', '3-Mobadeleh', '01-Mesghal', '01-Bahar', '02-Emami', '03-0.5 coin', '04-1/4 coin', '01-Yearly avg', '02-Monthly', '01-Broad Money', '04-Foreign Assets', '03-Government Debt', '05-Privet Sector Debt', '06-Other Sources', '02-Currency Circulation', '01-Monetary Base', '02-Foreign Assets', '04-Bankks Debt', '05-Other Sources', '06-Reserves', '07-Deposits', '08-Currency Circulation', '03-LF Population (+15)', '02-Participation rate', '01-Unemployment rate', '01-Total', '02-Oil', '03-Gas', '04-Hydropower', '05-Other supply', '03-Export', '04-Import', '01-Production', '02-Consumption', '05-Gas flaring', '06-Network', '01-Country', '02-Province', '01-homicide', '02-suicide', '03-Others', '01-Under 13', '02-Under 15', '03-Under 18', '01-Value', '02-Weight', '01-Current Price', '02-Constant Price', '01-World Bank', '02-IMF', '03-Iran Cbi', '04-Iran Stats', '01-Nominal', '02-Share', '01-Total', '02-Food', '03-Non-food', '04-Housing', '01-Yearly avg', '02-Monthly', '01-Persian cal', '02-Gregorian cal', '01-M1: Money', '02-M2: Quasi money', '01-+15', '02-15-64', '03-15-24', '04-Educated', '01-Value', '02-Volume', '03-Floating', '04-Loading', '01-IEA', '02-Oil ministry', '02-Residential', '03-Transportation', '04-Agriculture', '05-Industrial', "06-Petrochemicals' fuel", '07-Power plants', '08-Non-energy', '01-Gasoline', '02-Diesel', '03-Fuel oil', '04-Kerosene', '02-Oil products', '01-Country', '02-Provincial', '03-Refineries', '01-Total Population', '02-Age Groupe', '01-Urban & Rural', '02-Urban', '03-Rural', '01-Yearly', '01-Private places', '02-Public places', '03-Houses', '04-Stores', '05-Vehicles ', '06-Motorcycles', '07-Vehicles interior items', '08-Cattles', '09-Arrested', '02-Province', '01-World Bank', '02-IMF', '03-Iran CBI', '04-Iran Stats', '01-Yearly', '02-Seasonal', '01-With oil', '02-Without oil', '01-Iran Stats', '02-Iran CBI', '03-World Bank', '04-IMF', '01-Persian cal', '02-Gregorian cal', '01-Male & female', '02-Female', '03-Male', '01-OPEC', '01-Total', '02-to China', '03-Other Countries', '01-Raw gas', '02-Light gas', '03-Re-injection', '01-IEA', '02-Oil ministry', '02-LPG', '03-Gasoline', '04-Diesel', '05-Fuel oil', '06-Kerosene', '01-Gasoline', '02-Diesel', '03-Mazut', '01-Refineries Share', '02-Refineries Stats', '01-Urban & Rural', '02-Urban', '03-Rural', '01-Male & Female', '02-Male', '03-Female', '01-$', '02-IRR', '01-Yearly', '02-Seasonal', '03-Month to month', '02-Point-to-point', '01-12 month', 'Yearly', 'Monthly', '1395=100', '1400=100', '01-ILO estimate', '02-National estimate', '01-Persian Gulf', '02-Tehran', '03-Bandar Abbas', '04-Isfahan', '05-Shiraz', '06-Lavan', '07-Shazand', '08-Tabriz', '09-Kermanshah', '01-Male & Female', '02-Male', '03-Female', '03-Month to month', '02-Point-to-point', '01-12 month', '01-Economy', '06-Markets', '05-Energy', '02-Social', '03-Health', '07-Trade', '01-اقتصاد کلان', '06-بازار', '05-انرژی', '02-اجتماعی', '03-سلامت', '07-تحارت گمرکی']
239 ['GDP', 'Inflation', 'Exchange', 'Gold', 'Stock', 'Monetary', 'Labour force', 'Supply & Demand', 'Oil & Gas', 'Population', 'Vital', 'Harms', 'Life expectancy', 'by Country', 'by Customs', 'Total Value', 'Per capita', 'National', 'Provincial', 'USD $', 'Weighted', 'Coin', 'ran Stock Market', 'Broad money', 'Monetary base', 'Supply', 'Demand', 'OIl', 'Natural gas', 'Petrolium', 'Population', 'Household', 'Marriage', 'Divorce', 'Birth', 'Death', 'Rubbery', 'Suspicious Deaths', 'Child marriage', 'Male & Female', 'Male', 'Female', 'Export', 'Import', 'Total trade', 'Nominal', 'PPP', 'Growth', 'Provincial', 'Rate', 'CPI', 'ree price', 'ima', 'obadeleh', 'Mesghal', 'Bahar', 'Emami', '0.5 coin', '1/4 coin', 'Yearly avg', 'Monthly', 'Broad Money', 'Foreign Assets', 'Government Debt', 'Privet Sector Debt', 'Other Sources', 'Currency Circulation', 'Monetary Base', 'Foreign Assets', 'Bankks Debt', 'Other Sources', 'Reserves', 'Deposits', 'Currency Circulation', 'LF Population (+15)', 'Participation rate', 'Unemployment rate', 'Total', 'Oil', 'Gas', 'Hydropower', 'Other supply', 'Export', 'Import', 'Production', 'Consumption', 'Gas flaring', 'Network', 'Country', 'Province', 'homicide', 'suicide', 'Others', 'Under 13', 'Under 15', 'Under 18', 'Value', 'Weight', 'Current Price', 'Constant Price', 'World Bank', 'IMF', 'Iran Cbi', 'Iran Stats', 'Nominal', 'Share', 'Total', 'Food', 'Non-food', 'Housing', 'Yearly avg', 'Monthly', 'Persian cal', 'Gregorian cal', 'M1: Money', 'M2: Quasi money', '+15', '15-64', '15-24', 'Educated', 'Value', 'Volume', 'Floating', 'Loading', 'IEA', 'Oil ministry', 'Residential', 'Transportation', 'Agriculture', 'Industrial', "Petrochemicals' fuel", 'Power plants', 'Non-energy', 'Gasoline', 'Diesel', 'Fuel oil', 'Kerosene', 'Oil products', 'Country', 'Provincial', 'Refineries', 'Total Population', 'Age Groupe', 'Urban & Rural', 'Urban', 'Rural', 'Yearly', 'Private places', 'Public places', 'Houses', 'Stores', 'Vehicles ', 'Motorcycles', 'Vehicles interior items', 'Cattles', 'Arrested', 'Province', 'World Bank', 'IMF', 'Iran CBI', 'Iran Stats', 'Yearly', 'Seasonal', 'With oil', 'Without oil', 'Iran Stats', 'Iran CBI', 'World Bank', 'IMF', 'Persian cal', 'Gregorian cal', 'Male & female', 'Female', 'Male', 'OPEC', 'Total', 'to China', 'Other Countries', 'Raw gas', 'Light gas', 'Re-injection', 'IEA', 'Oil ministry', 'LPG', 'Gasoline', 'Diesel', 'Fuel oil', 'Kerosene', 'Gasoline', 'Diesel', 'Mazut', 'Refineries Share', 'Refineries Stats', 'Urban & Rural', 'Urban', 'Rural', 'Male & Female', 'Male', 'Female', '$', 'IRR', 'Yearly', 'Seasonal', 'Month to month', 'Point-to-point', '12 month', 'rly', 'thly', '5=100', '0=100', 'ILO estimate', 'National estimate', 'Persian Gulf', 'Tehran', 'Bandar Abbas', 'Isfahan', 'Shiraz', 'Lavan', 'Shazand', 'Tabriz', 'Kermanshah', 'Male & Female', 'Male', 'Female', 'Month to month', 'Point-to-point', '12 month', 'Economy', 'Markets', 'Energy', 'Social', 'Health', 'Trade', 'اقتصاد کلان', 'بازار', 'انرژی', 'اجتماعی', 'سلامت', 'تحارت گمرکی']